Repository TempleEight/temple-docs, pull requests merged in 2020-05, with the labels that each got.

#33 [DSL] Add documentation for the Templefile format
  TempleEight/docs/reference/templefile-primitives.md
  TempleEight/docs/reference/templefile-spec.md
Labels: size/L

#36 [auth] Add identify endpoint
  TempleEight/docs/guide/authentication.md
Labels: size/S

#38 [Structs] Add docs on structs
  TempleEight/docs/guide/structs.md
  TempleEight/sidebars.js
Labels: size/L

#37 [DSL] Add #authMethod for services with #auth
  TempleEight/docs/reference/templefile-spec.md
Labels: size/XS

#42 [hooks] Replace ls with tree
  TempleEight/docs/guide/hooks.md
Labels: size/S

#41 [tidy] Fix cross-page links
  TempleEight/docs/guide/access-control.md
  TempleEight/docs/guide/adding-dao-functions.md
  TempleEight/docs/guide/adding-endpoints.md
  TempleEight/docs/guide/custom-handlers.md
  TempleEight/docs/guide/omitting-endpoints.md
  TempleEight/docs/guide/orchestration.md
  TempleEight/docs/guide/regeneration.md
  TempleEight/docs/guide/value-constraints.md
  TempleEight/docs/reference/templefile-spec.md
Labels: size/M

#35 [getting-started] Rewrite of getting started
  TempleEight/docs/getting-started.md
Labels: size/L

#43 [installation] Fix typo in repo name
  TempleEight/docs/installation.md
Labels: size/XS

#45 [installation] Bump version
  TempleEight/docs/installation.md
Labels: size/S

#46 [introduction] Add tweaks
  TempleEight/docs/introduction.md
Labels: size/M

#48 Update getting-started.md
  TempleEight/docs/getting-started.md
Labels: size/XS

#49 Update airbnb.md
  TempleEight/docs/reference/example-templefiles/airbnb.md
Labels: size/XS

#47 [installation] Fix URL for latest
  TempleEight/docs/installation.md
Labels: size/XS

#50 [getting-started] Rename simple.temple to example.temple
  TempleEight/docs/getting-started.md
Labels: size/XS
