Repository TempleEight/temple-docs, pull requests merged in 2020-04, with the labels that each got.

#2 Write getting started guide
  TempleEight/docs/getting-started.md
  TempleEight/docs/guide/access-control.md
  TempleEight/docs/guide/authentication.md
  TempleEight/docs/guide/cross-service-coms.md
  TempleEight/docs/guide/enumeration.md
  TempleEight/docs/guide/getting-started.md
  TempleEight/docs/guide/metrics.md
  TempleEight/docs/guide/orchestration.md
  TempleEight/docs/guide/value-annotations.md
  TempleEight/docs/installation.md
  TempleEight/docs/reference/contents.md
  TempleEight/docs/reference/primitives.md
  TempleEight/docs/reference/templefile-spec.md
  TempleEight/docs/welcome.md
  TempleEight/sidebars.js
  TempleEight/static/img/microservice-architecture.png
  TempleEight/static/img/tutorial-architecture.png
Labels: size/L

#3 [business-logic] Add first section of business logic
  TempleEight/docs/guide/business-logic.md
  TempleEight/sidebars.js
Labels: size/M

#4 [business-logic] Add more business logic section
  TempleEight/docs/guide/business-logic.md
  TempleEight/docs/guide/custom-handlers.md
  TempleEight/sidebars.js
Labels: size/L

#5 [config] Fix name in config
  TempleEight/docusaurus.config.js
Labels: size/XS

#7 [config] Fix base url
  TempleEight/docusaurus.config.js
Labels: size/XS

#6 [blog] Remove blog
  TempleEight/blog/2019-05-30-welcome.md
  TempleEight/docusaurus.config.js
Labels: size/S

#8 [refactor] Add full docs outline
  TempleEight/docs/arch/service.md
  TempleEight/docs/arch/system.md
  TempleEight/docs/getting-started.md
  TempleEight/docs/guide/adding-dao-functions.md
  TempleEight/docs/guide/adding-endpoints.md
  TempleEight/docs/guide/authentication.md
  TempleEight/docs/guide/cross-service-coms.md
  TempleEight/docs/guide/foreign-keys.md
  TempleEight/docs/guide/hooks.md
  TempleEight/docs/guide/metrics.md
  TempleEight/docs/guide/omitting-endpoints.md
  TempleEight/docs/guide/orchestration.md
  TempleEight/docs/guide/regeneration.md
  TempleEight/docs/guide/temple-test.md
  TempleEight/docs/installation.md
  TempleEight/docs/introduction.md
  TempleEight/docs/reference/contents.md
  TempleEight/docs/reference/example-templefiles/airbnb.md
  TempleEight/docs/reference/templefile-primitives.md
  TempleEight/docusaurus.config.js
  TempleEight/sidebars.js
  TempleEight/src/pages/index.js
Labels: size/L

#15 [omit] Add documentation for omitting endpoints
  TempleEight/docs/guide/omitting-endpoints.md
Labels: size/M

#16 [enumeration] Add enumeration guide
  TempleEight/docs/guide/enumeration.md
Labels: size/L

#13 [endpoints] Add docs for adding new endpoint
  TempleEight/docs/guide/adding-endpoints.md
  TempleEight/docs/guide/hooks.md
Labels: size/L

#12 [dao] Add new DAO method documentation
  TempleEight/docs/guide/adding-dao-functions.md
  TempleEight/docs/guide/hooks.md
Labels: size/M

#10 [docs] Add regeneration section
  TempleEight/docs/guide/regeneration.md
Labels: size/M

#18 [examples] Add some example templefiles
  TempleEight/docs/reference/example-templefiles/airbnb.md
  TempleEight/docs/reference/example-templefiles/amazon.md
  TempleEight/docs/reference/example-templefiles/deliveroo.md
  TempleEight/docs/reference/example-templefiles/five-a-side.md
  TempleEight/docs/reference/example-templefiles/lockdown-shopping.md
  TempleEight/sidebars.js
Labels: size/L

#19 [foreign] Add foreign key docs
  TempleEight/docs/guide/foreign-keys.md
Labels: size/M

#9 [docs] Add value constraints section
  TempleEight/docs/getting-started.md
  TempleEight/docs/guide/hooks.md
  TempleEight/docs/guide/value-annotations.md
  TempleEight/docs/guide/value-constraints.md
  TempleEight/sidebars.js
Labels: size/M

#17 [install] Add docker installation
  TempleEight/docs/installation.md
Labels: size/M

#23 [dsl] Fix case on Templefile
  TempleEight/docs/introduction.md
  TempleEight/docs/reference/templefile-primitives.md
  TempleEight/docs/reference/templefile-spec.md
  TempleEight/src/pages/index.js
Labels: size/M

#27 [sidebar] Order sidebar alphabetically
  TempleEight/sidebars.js
Labels: size/S

#29 [installation] Bump versions in installation guide
  TempleEight/docs/installation.md
Labels: size/S

#24 [temple-test] Add documentation
  TempleEight/docs/guide/temple-test.md
Labels: size/M

#30 [orchestration] add information about registry.me workaround
  TempleEight/docs/guide/orchestration.md
Labels: size/S

#31 [hotfix] fix port docker registry
  TempleEight/docs/guide/orchestration.md
Labels: size/XS

#25 Value annotations
  TempleEight/docs/getting-started.md
  TempleEight/docs/guide/hooks.md
  TempleEight/docs/guide/value-annotations.md
  TempleEight/docs/guide/value-constraints.md
  TempleEight/sidebars.js
Labels: size/L

#32 [Docs] Add syntax highlighting for Templefiles
  TempleEight/docs/arch/service.md
  TempleEight/docs/getting-started.md
  TempleEight/docs/guide/adding-dao-functions.md
  TempleEight/docs/guide/authentication.md
  TempleEight/docs/guide/enumeration.md
  TempleEight/docs/guide/foreign-keys.md
  TempleEight/docs/guide/omitting-endpoints.md
  TempleEight/docs/guide/value-annotations.md
  TempleEight/docs/guide/value-constraints.md
  TempleEight/docs/reference/example-templefiles/airbnb.md
  TempleEight/docs/reference/example-templefiles/amazon.md
  TempleEight/docs/reference/example-templefiles/deliveroo.md
  TempleEight/docs/reference/example-templefiles/five-a-side.md
  TempleEight/docs/reference/example-templefiles/lockdown-shopping.md
  TempleEight/docusaurus.config.js
  TempleEight/package-lock.json
  TempleEight/package.json
  TempleEight/src/templefile/index.js
  TempleEight/src/templefile/templefile.js
Labels: size/L

#28 [access-control] Add access control docs
  TempleEight/docs/arch/service.md
  TempleEight/docs/guide/access-control.md
Labels: size/L
